# Placeholder hardware configuration for nuc.
# Replace this file with the one generated by:
#   sudo nixos-generate-config --root /mnt
# and copy the resulting /mnt/etc/nixos/hardware-configuration.nix here.
# Keep it version-controlled to ensure reproducibility.
{ config, lib, pkgs, ... }:
{
}
